services:
  label-studio:
    build: .
    image: cs4337-label-studio:1.23.2
    container_name: cs4337-label-studio

    ports:
      - "127.0.0.1:8080:8080"

    environment:
      LABEL_STUDIO_USERNAME: ${LABEL_STUDIO_USERNAME:-}
      LABEL_STUDIO_PASSWORD: ${LABEL_STUDIO_PASSWORD:-}

      LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED: "true"
      LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT: /label-studio/files/annotation

    volumes:
      # Label Studio projects, annotations, database, etc.
      - label-studio-data:/label-studio/data

      # Existing dataset on the server
      - ../data/annotation:/label-studio/files/annotation:ro

      # Labeling interface XML files
      - ./label_configs:/label_configs:ro

    restart: unless-stopped

volumes:
  label-studio-data:
  